# -*- coding: utf-8 -*-
"""DeepLearningTraining.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AygPxpmiK9UelEmQMhXDijpzSKxPiwJ4

ordinary least squares,OLS
"""

import numpy as np
import matplotlib.pyplot as plt

x = np.array([2,4,6,8])
y = np.array([81,93,91,97])

mx = np.mean(x)
my = np.mean(y)
print(mx,my)

divisor=sum([(i-mx)**2 for i in x])
def top(x,mx,y,my):
  d = 0
  for i in range(len(x)):
    d+= (x[i]-mx)*(y[i]-my)
  return d
dividend = top(x,mx,y,my)

print(divisor,dividend)
a=dividend/divisor
b = my-(mx*a)
print("a=",a)
print("b=",b)

plt.plot(x,y,'o')
plt.plot(x,(a*x+b))
plt.show()